{
    'name': 'Avicampo Validacion',
    'version': '1.0.0',
    'author': "Marco Gonzalez",    
    'category': "Tools",
    'website': 'www.grupoalvamex.com',
    'license': 'LGPL-3',
    'summary': 'Validacion de transferecias y presupuestos de compra',
    'depends': ['account','stock', 'purchase'],
    'description': """ """,
    'demo': [],
    'data': ['views/validacion_view.xml',
        'views/validacion_compras_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}
